Repository ahmadAria001/KawanDesa, pull requests merged in 2024-05, with the labels that each got.

#20 Bug and Features
  app/Http/Controllers/CivilianController.php
  app/Http/Controllers/PasswordController.php
  app/Http/Controllers/ProfileImageController.php
  app/Http/Controllers/UserController.php
  app/Http/Middleware/Resources/Password/Reset.php
  app/Http/Middleware/Resources/User/Pict/Create.php
  app/Http/Middleware/Resources/User/Pict/Delete.php
  app/Http/Middleware/Resources/User/Pict/Get.php
  app/Http/Middleware/Resources/User/Pict/Update.php
  app/Http/Requests/Resources/Password/Reset.php
  app/Http/Requests/Resources/User/Pict/Create.php
  app/Http/Requests/Resources/User/Pict/Update.php
  app/Models/User.php
  composer.json
  composer.lock
  config/image.php
  database/migrations/2024_04_02_063121_create_users_table.php
  public/assets/uploads/2024-05-14 06:49:58_wallpaperflare.com_wallpaper.jpg
  resources/js/Components/PendudukByRT/Modals/Edit.svelte
  resources/js/Components/Profile/GeneralInfo.svelte
  resources/js/Components/Profile/Password.svelte
  resources/js/Components/Profile/Pict.svelte
  resources/js/Components/Profile/Pict/Modal.svelte
  resources/js/Pages/ArsipPenduduk.svelte
  resources/js/Pages/Layout.svelte
  resources/js/Pages/PendudukByRT.svelte
  resources/js/Pages/Profile.svelte
  resources/js/Utils/Schema/Pict/Create.ts
  resources/js/Utils/Schema/User/Password/Reset.ts
  routes/Handler/API/auth.php
  routes/Handler/API/civiliant.php
  routes/Handler/API/user.php
Labels: enhancement, dependencies

#28 fix: gitignore
  .gitignore
  public/assets/uploads/2024-05-14 06:49:58_wallpaperflare.com_wallpaper.jpg
Labels: bug

#19 feat: add landing page
  resources/js/Components/LandingPage/cards/CardsAnnouncement.svelte
  resources/js/Components/LandingPage/nav/Navbar.svelte
  resources/js/Components/PendudukByRT/Modals/Create.svelte
  resources/js/Components/Profile/Password.svelte
  resources/js/Pages/LandingPage.svelte
  resources/js/Pages/LandingPagePengumuman.svelte
  resources/js/Pages/Layout.svelte
  resources/js/Pages/Login.svelte
  resources/js/Pages/Page404.svelte
  resources/js/Pages/PendudukByRT.svelte
  resources/js/Pages/StatusPengaduan.svelte
  resources/views/app.blade.php
  routes/web.php
Labels: bug, enhancement
